version: "2.2"

services:
  mysql:
    image: mysql:8.2
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=discordbot
      - MYSQL_PASSWORD=discordbot
      - MYSQL_DATABASE=discordbot
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    profiles:
      - mysql
  postgres:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=discordbot
      - POSTGRES_USER=discordbot
      - POSTGRES_DB=discordbot
    profiles:
      - postgres
