DROP TABLE owners IF EXISTS;

CREATE TABLE owners (
                        id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        first_name VARCHAR(30),
                        last_name  VARCHAR_IGNORECASE(30),
                        address    VARCHAR(255),
                        city       VARCHAR(80),
                        telephone  VARCHAR(20)
);
CREATE INDEX owners_last_name ON owners (last_name);